WITH eligible_cars AS (
    SELECT 
        c.CAR_ID,
        c.CAR_TYPE,
        c.DAILY_FEE,
        d.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR AS c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS d 
        ON c.CAR_TYPE = d.CAR_TYPE AND d.DURATION_TYPE = '30일 이상'
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
        AND c.CAR_ID NOT IN (
            SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
        )
)
SELECT 
    CAR_ID,
    CAR_TYPE,
    ROUND((DAILY_FEE * (1 - DISCOUNT_RATE / 100)) * 30, 0) AS FEE
FROM eligible_cars
WHERE ROUND((DAILY_FEE * (1 - DISCOUNT_RATE / 100)) * 30, 0) >= 500000 
  AND ROUND((DAILY_FEE * (1 - DISCOUNT_RATE / 100)) * 30, 0) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
