-- 코드를 작성해주세요
select FISH_INFO.ID, FISH_NAME_INFO.FISH_NAME, FISH_INFO.LENGTH
from FISH_INFO
    join FISH_NAME_INFO on FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
where FISH_INFO.FISH_TYPE in
    (select FISH_TYPE from FISH_INFO group by FISH_TYPE having LENGTH = max(LENGTH))
order by FISH_INFO.ID