-- 조회수가 가장 높은 게시물의 BOARD_ID 가져오기
WITH MAX_VIEWED_BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
-- 첨부파일 경로 구성
SELECT 
    CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS f
JOIN MAX_VIEWED_BOARD AS m ON f.BOARD_ID = m.BOARD_ID
ORDER BY f.FILE_ID DESC;
